In [1]:
import pandas as pd
import numpy as np

from sklearn.linear_model import LinearRegression

In [2]:
df = pd.read_csv('data_science_job.csv')

In [3]:
df.head()

enrollee_id      city  city_development_index gender  \
0         8949  city_103                   0.920   Male   
1        29725   city_40                   0.776   Male   
2        11561   city_21                   0.624    NaN   
3        33241  city_115                   0.789    NaN   
4          666  city_162                   0.767   Male   

       relevent_experience enrolled_university education_level  \
0  Has relevent experience       no_enrollment        Graduate   
1   No relevent experience       no_enrollment        Graduate   
2   No relevent experience    Full time course        Graduate   
3   No relevent experience                 NaN        Graduate   
4  Has relevent experience       no_enrollment         Masters   

  major_discipline  experience company_size    company_type  training_hours  \
0             STEM        20.0          NaN             NaN            36.0   
1             STEM        15.0        50-99         Pvt Ltd            47.0   
2             STEM         5.0          NaN             NaN            83.0   
3  Business Degree         0.0          NaN         Pvt Ltd            52.0   
4             STEM        20.0        50-99  Funded Startup             8.0   

   target  
0     1.0  
1     0.0  
2     0.0  
3     1.0  
4     0.0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19158 entries, 0 to 19157
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   enrollee_id             19158 non-null  int64  
 1   city                    19158 non-null  object 
 2   city_development_index  18679 non-null  float64
 3   gender                  14650 non-null  object 
 4   relevent_experience     19158 non-null  object 
 5   enrolled_university     18772 non-null  object 
 6   education_level         18698 non-null  object 
 7   major_discipline        16345 non-null  object 
 8   experience              19093 non-null  float64
 9   company_size            13220 non-null  object 
 10  company_type            13018 non-null  object 
 11  training_hours          18392 non-null  float64
 12  target                  19158 non-null  float64
dtypes: float64(4), int64(1), object(8)
memory usage: 1.9+ MB


In [5]:
df.isnull().mean() * 100

enrollee_id                0.000000
city                       0.000000
city_development_index     2.500261
gender                    23.530640
relevent_experience        0.000000
enrolled_university        2.014824
education_level            2.401086
major_discipline          14.683161
experience                 0.339284
company_size              30.994885
company_type              32.049274
training_hours             3.998330
target                     0.000000
dtype: float64

In [6]:
df.drop(columns=['enrollee_id','city','gender','relevent_experience','enrolled_university','education_level','major_discipline','company_size','company_type'],inplace=True)
df = df.sample(5)
df

city_development_index  experience  training_hours  target
6223                    0.827        10.0             4.0     0.0
17885                   0.624         6.0            80.0     1.0
10675                   0.920        12.0            74.0     0.0
8839                    0.920        11.0            61.0     1.0
5113                    0.920        20.0            84.0     0.0

In [7]:
df = df.iloc[:,0:-1]
df

city_development_index  experience  training_hours
6223                    0.827        10.0             4.0
17885                   0.624         6.0            80.0
10675                   0.920        12.0            74.0
8839                    0.920        11.0            61.0
5113                    0.920        20.0            84.0

In [8]:
df.iloc[1,0] = np.NaN
df.iloc[3,1] = np.NaN
df.iloc[-1,-1] = np.NaN

C:\Users\Duy.TC214885\AppData\Local\Temp\ipykernel_4660\2040708130.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.iloc[1,0] = np.NaN
C:\Users\Duy.TC214885\AppData\Local\Temp\ipykernel_4660\2040708130.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.iloc[3,1] = np.NaN
C:\Users\Duy.TC214885\AppData\Local\Temp\ipykernel_4660\2040708130.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.iloc[-1,-1] = np.NaN


In [9]:
df.head()

city_development_index  experience  training_hours
6223                    0.827        10.0             4.0
17885                     NaN         6.0            80.0
10675                   0.920        12.0            74.0
8839                    0.920         NaN            61.0
5113                    0.920        20.0             NaN

In [10]:
# Step 1 - Impute all missing values with mean of respective col

df0 = pd.DataFrame()

df0['city_development_index'] = df['city_development_index'].fillna(df['city_development_index'].mean())
df0['experience'] = df['experience'].fillna(df['experience'].mean())
df0['training_hours'] = df['training_hours'].fillna(df['training_hours'].mean())

In [11]:
# 0th Iteration
df0

city_development_index  experience  training_hours
6223                  0.82700        10.0            4.00
17885                 0.89675         6.0           80.00
10675                 0.92000        12.0           74.00
8839                  0.92000        12.0           61.00
5113                  0.92000        20.0           54.75

In [12]:
# Remove the col1 imputed value
df1 = df0.copy()

df1.iloc[1,0] = np.NaN

df1

city_development_index  experience  training_hours
6223                    0.827        10.0            4.00
17885                     NaN         6.0           80.00
10675                   0.920        12.0           74.00
8839                    0.920        12.0           61.00
5113                    0.920        20.0           54.75

In [13]:
# Use first 3 rows to build a model and use the last for prediction

X = df1.iloc[[0,2,3,4],1:4]
X

experience  training_hours
6223         10.0            4.00
10675        12.0           74.00
8839         12.0           61.00
5113         20.0           54.75

In [14]:
y = df1.iloc[[0,2,3,4],0]
y

6223     0.827
10675    0.920
8839     0.920
5113     0.920
Name: city_development_index, dtype: float64

In [15]:
lr = LinearRegression()
lr.fit(X,y)
lr.predict(df1.iloc[1,1:].values.reshape(1,2))

C:\Users\Duy.TC214885\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([0.92177047])

In [16]:
df1.iloc[1,0] = 0.92
df1

city_development_index  experience  training_hours
6223                    0.827        10.0            4.00
17885                   0.920         6.0           80.00
10675                   0.920        12.0           74.00
8839                    0.920        12.0           61.00
5113                    0.920        20.0           54.75

In [17]:
# Remove the col2 imputed value

df1.iloc[3,1] = np.NaN

df1

city_development_index  experience  training_hours
6223                    0.827        10.0            4.00
17885                   0.920         6.0           80.00
10675                   0.920        12.0           74.00
8839                    0.920         NaN           61.00
5113                    0.920        20.0           54.75

In [18]:
# Use last 3 rows to build a model and use the first for prediction
X = df1.iloc[[0,1,2,4],[0,2]]
X

city_development_index  training_hours
6223                    0.827            4.00
17885                   0.920           80.00
10675                   0.920           74.00
5113                    0.920           54.75

In [19]:
y = df1.iloc[[0,1,2,4],1]
y

6223     10.0
17885     6.0
10675    12.0
5113     20.0
Name: experience, dtype: float64

In [20]:
lr = LinearRegression()
lr.fit(X,y)
lr.predict(df1.iloc[3,[0,2]].values.reshape(1,2))

C:\Users\Duy.TC214885\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([17.13456243])

In [21]:
df1.iloc[3,1] = 6.44
df1

city_development_index  experience  training_hours
6223                    0.827       10.00            4.00
17885                   0.920        6.00           80.00
10675                   0.920       12.00           74.00
8839                    0.920        6.44           61.00
5113                    0.920       20.00           54.75

In [22]:
# Remove the col3 imputed value
df1.iloc[4,-1] = np.NaN

df1

city_development_index  experience  training_hours
6223                    0.827       10.00             4.0
17885                   0.920        6.00            80.0
10675                   0.920       12.00            74.0
8839                    0.920        6.44            61.0
5113                    0.920       20.00             NaN

In [23]:
# Use last 3 rows to build a model and use the first for prediction
X = df1.iloc[0:4,0:2]
X

city_development_index  experience
6223                    0.827       10.00
17885                   0.920        6.00
10675                   0.920       12.00
8839                    0.920        6.44

In [24]:
y = df1.iloc[0:4,-1]
y

6223      4.0
17885    80.0
10675    74.0
8839     61.0
Name: training_hours, dtype: float64

In [25]:
lr = LinearRegression()
lr.fit(X,y)
lr.predict(df1.iloc[4,0:2].values.reshape(1,2))

C:\Users\Duy.TC214885\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([76.59825473])

In [26]:
df1.iloc[4,-1] = 52.08
df1

city_development_index  experience  training_hours
6223                    0.827       10.00            4.00
17885                   0.920        6.00           80.00
10675                   0.920       12.00           74.00
8839                    0.920        6.44           61.00
5113                    0.920       20.00           52.08

In [27]:
# Subtract 0th iteration from 1st iteration

df1 - df0

city_development_index  experience  training_hours
6223                  0.00000        0.00            0.00
17885                 0.02325        0.00            0.00
10675                 0.00000        0.00            0.00
8839                  0.00000       -5.56            0.00
5113                  0.00000        0.00           -2.67

In [28]:
df2 = df1.copy()

df2.iloc[1,0] = np.NaN

df2

city_development_index  experience  training_hours
6223                    0.827       10.00            4.00
17885                     NaN        6.00           80.00
10675                   0.920       12.00           74.00
8839                    0.920        6.44           61.00
5113                    0.920       20.00           52.08

In [29]:
X = df2.iloc[[0,2,3,4],1:3]
y = df2.iloc[[0,2,3,4],0]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df2.iloc[1,1:].values.reshape(1,2))

C:\Users\Duy.TC214885\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([0.93509679])

In [30]:
df2.iloc[1,0] = 0.92

In [31]:
df2.iloc[3,1] = np.NaN
X = df2.iloc[[0,1,2,4],[0,2]]
y = df2.iloc[[0,1,2,4],1]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df2.iloc[3,[0,2]].values.reshape(1,2))

C:\Users\Duy.TC214885\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([16.24165687])

In [32]:
df2.iloc[3,1] = 6.56
df2

city_development_index  experience  training_hours
6223                    0.827       10.00            4.00
17885                   0.920        6.00           80.00
10675                   0.920       12.00           74.00
8839                    0.920        6.56           61.00
5113                    0.920       20.00           52.08

In [33]:
df2.iloc[4,-1] = np.NaN

X = df2.iloc[0:4,0:2]
y = df2.iloc[0:4,-1]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df2.iloc[4,0:2].values.reshape(1,2))

C:\Users\Duy.TC214885\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([75.9828122])

In [34]:
df2.iloc[4,-1] = 51.56
df2

city_development_index  experience  training_hours
6223                    0.827       10.00            4.00
17885                   0.920        6.00           80.00
10675                   0.920       12.00           74.00
8839                    0.920        6.56           61.00
5113                    0.920       20.00           51.56

In [35]:
df2 - df1

city_development_index  experience  training_hours
6223                      0.0        0.00            0.00
17885                     0.0        0.00            0.00
10675                     0.0        0.00            0.00
8839                      0.0        0.12            0.00
5113                      0.0        0.00           -0.52

In [36]:
df3 = df2.copy()

df3.iloc[1,0] = np.NaN

df3

city_development_index  experience  training_hours
6223                    0.827       10.00            4.00
17885                     NaN        6.00           80.00
10675                   0.920       12.00           74.00
8839                    0.920        6.56           61.00
5113                    0.920       20.00           51.56

In [37]:
X = df3.iloc[[0,2,3,4],1:3]
y = df3.iloc[[0,2,3,4],0]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df3.iloc[1,1:].values.reshape(1,2))

C:\Users\Duy.TC214885\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([0.9346508])

In [38]:
df3.iloc[1,0] = 0.92

In [39]:
df3.iloc[3,1] = np.NaN
X = df3.iloc[[0,1,2,4],[0,2]]
y = df3.iloc[[0,1,2,4],1]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df3.iloc[3,[0,2]].values.reshape(1,2))

C:\Users\Duy.TC214885\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([16.08918032])

In [40]:
df3.iloc[3,1] = 6.57
df3

city_development_index  experience  training_hours
6223                    0.827       10.00            4.00
17885                   0.920        6.00           80.00
10675                   0.920       12.00           74.00
8839                    0.920        6.57           61.00
5113                    0.920       20.00           51.56

In [41]:
df3.iloc[4,-1] = np.NaN

X = df3.iloc[0:4,0:2]
y = df3.iloc[0:4,-1]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df3.iloc[4,0:2].values.reshape(1,2))

C:\Users\Duy.TC214885\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([75.93055442])

In [42]:
df3.iloc[4,-1] = 51.5
df3

city_development_index  experience  training_hours
6223                    0.827       10.00             4.0
17885                   0.920        6.00            80.0
10675                   0.920       12.00            74.0
8839                    0.920        6.57            61.0
5113                    0.920       20.00            51.5

In [43]:
df2.iloc[3,1] = 51.56

In [44]:
df3 - df2

city_development_index  experience  training_hours
6223                      0.0        0.00            0.00
17885                     0.0        0.00            0.00
10675                     0.0        0.00            0.00
8839                      0.0      -44.99            0.00
5113                      0.0        0.00           -0.06

In [45]:
df

city_development_index  experience  training_hours
6223                    0.827        10.0             4.0
17885                     NaN         6.0            80.0
10675                   0.920        12.0            74.0
8839                    0.920         NaN            61.0
5113                    0.920        20.0             NaN